name: Docker Build & Test CI

# 1. ¿Cuando se ejecuta? Cuando hay un push a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    # 2. ¿En que sistema corre? Usamos ubuntu
    runs-on: ubuntu-latest

    steps:
      # 3. Descarga el código en la VM
      - name: Checkout code
        uses: actions/checkout@v3

      # 4. Credenciales de Login en Docker usando secrets de gitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Configura el entorno de Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: santivag/incident-manager-api:latest
